name: rust nightly

on:
    repository_dispatch:
        types: nightly-release
    schedule:
        - cron: '0 2 * * *'

jobs:
    generate-build-number:
        runs-on: ubuntu-latest
        outputs:
            build_number: ${{ steps.buildnumber.outputs.build_number }}
        steps:
            - name: Generate build number
              uses: einaregilsson/build-number@v2
              id: buildnumber
              with:
                  token: ${{ secrets.github_token }}
                  prefix: rust

    build:
        needs: generate-build-number
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                platform-version: [ 201, 202 ]
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                  java-version: 1.8

            - name: Set up env variables
              # see https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
              run: |
                  echo "::set-env name=CI::true"
                  echo "::set-env name=ORG_GRADLE_PROJECT_buildNumber::${{ needs.generate-build-number.outputs.build_number }}"
                  echo "::set-env name=ORG_GRADLE_PROJECT_platformVersion::${{ matrix.platform-version }}"
                  echo "::set-env name=ORG_GRADLE_PROJECT_enableBuildSearchableOptions::true"
                  echo "::set-env name=ORG_GRADLE_PROJECT_publishChannel::nightly"
                  echo "::set-env name=ORG_GRADLE_PROJECT_publishToken::${{ secrets.plugin_bot_token }}"

            - name: Publish rust plugin
              uses: eskatos/gradle-command-action@v1
              with:
                  arguments: :plugin:publishPlugin

            - name: Publish toml plugin
              uses: eskatos/gradle-command-action@v1
              with:
                  arguments: :intellij-toml:publishPlugin
